<?xml version="1.0" encoding = "utf-8" ?>
    <!DOCTYPE TS >
    <TS version="2.1" language = "vi" >
        <context>
        <name>TesterController </name>
        < message > <source>Success < /source><translation>Thành công</translation > </message>
        < message > <source>Error < /source><translation>Lỗi</translation > </message>
        < message > <source>Notice < /source><translation>Thông báo</translation > </message>
        < message > <source>Connected to port { 0 }.</source><translation>Đã kết nối tới cổng {0}.</translation > </message>
            < message > <source>Could not connect to { 0 }.\nCheck the port and device.< /source><translation>Không thể kết nối tới {0}.\nKiểm tra cổng và thiết bị.</translation > </message>
                < message > <source>Connection error < /source><translation>Lỗi kết nối</translation > </message>
                    < message > <source>Disconnected.< /source><translation>Đã ngắt kết nối.</translation > </message>
                    < message > <source>Not connected to Modbus.< /source><translation>Chưa kết nối Modbus.</translation > </message>
                        < message > <source>Scan stopped.< /source><translation>Đã dừng quét.</translation > </message>
                            < message > <source>Scan complete < /source><translation>Quét xong</translation > </message>
                                < message > <source>Scan finished.Found { 0 } register(s) with values.< /source><translation>Đã quét xong. Tìm thấy {0} thanh ghi có giá trị.</translation > </message>
                                </context>
                                < context >
                                <name>Main.qml </name>
                                < message > <source>Data Logger < /source><translation>Data Logger</translation > </message>
                                    < message > <source>Modbus tester < /source><translation>Thử Modbus</translation > </message>
                                        < message > <source>Dashboard < /source><translation>Dashboard</translation > </message>
                                        < message > <source>History < /source><translation>Lịch sử</translation > </message>
                                        < message > <source>Settings < /source><translation>Cài đặt</translation > </message>
                                        < message > <source>Exit < /source><translation>Thoát</translation > </message>
                                        < message > <source>FTP off < /source><translation>FTP tắt</translation > </message>
                                            < message > <source>FTP(% 1 pending) < /source><translation>FTP (%1 chờ)</translation > </message>
                                            < message > <source>FTP < /source><translation>FTP</translation > </message>
                                            </context>
                                            < context >
                                            <name>TesterView.qml </name>
                                            < message > <source>Save new sensor < /source><translation>Lưu cấu hình cảm biến mới</translation > </message>
                                                < message > <source>Name: </source><translation>Tên:</translation > </message>
                                                    < message > <source>Unit: </source><translation>Đơn vị:</translation > </message>
                                                        < message > <source>Coefficients(JSON): </source><translation>Hệ số (JSON):</translation > </message>
                                                            < message > <source>Poll interval(s): </source><translation>Chu kỳ đọc (s):</translation > </message>
                                                                < message > <source>Report column: </source><translation>Cột báo cáo:</translation > </message>
                                                                    < message > <source>Slave ID: </source><translation>Slave ID:</translation > </message>
                                                                        < message > <source>Start address: </source><translation>Địa chỉ bắt đầu:</translation > </message>
                                                                            < message > <source>Register type: </source><translation>Kiểu thanh ghi:</translation > </message>
                                                                                < message > <source>Data type: </source><translation>Kiểu dữ liệu:</translation > </message>
                                                                                    < message > <source>Cancel < /source><translation>Hủy</translation > </message>
                                                                                    < message > <source>Save sensor < /source><translation>Lưu cảm biến</translation > </message>
                                                                                        < message > <source>Error < /source><translation>Lỗi</translation > </message>
                                                                                        < message > <source>Configuration is still loading.Try again.< /source><translation>Cấu hình đang tải. Thử lại.</translation > </message>
                                                                                            < message > <source>Could not load configuration tabs.< /source><translation>Không tải được các tab cấu hình.</translation > </message>
                                                                                                < message > <source>Not connected to Modbus.< /source><translation>Chưa kết nối Modbus.</translation > </message>
                                                                                                    < message > <source>Start address must be less than or equal to end address.< /source><translation>Địa chỉ bắt đầu phải nhỏ hơn hoặc bằng địa chỉ kết thúc.</translation > </message>
                                                                                                        < message > <source>Connection < /source><translation>Kết nối</translation > </message>
                                                                                                        < message > <source>Operations < /source><translation>Thao tác</translation > </message>
                                                                                                        < message > <source>Scan results < /source><translation>Kết quả quét</translation > </message>
                                                                                                            < message > <source>Address < /source><translation>Địa chỉ</translation > </message>
                                                                                                            < message > <source>Value < /source><translation>Giá trị</translation > </message>
                                                                                                            </context>
                                                                                                            < context >
                                                                                                            <name>TesterConnectionTab.qml </name>
                                                                                                            < message > <source>Port: </source><translation>Cổng:</translation > </message>
                                                                                                                < message > <source>Refresh port list < /source><translation>Làm mới danh sách cổng</translation > </message>
                                                                                                                    < message > <source>Baud rate: </source><translation>Baudrate:</translation > </message>
                                                                                                                        < message > <source>Parity: </source><translation>Parity:</translation > </message>
                                                                                                                            < message > <source>Data bits: </source><translation>Data bits:</translation > </message>
                                                                                                                                < message > <source>Stop bits: </source><translation>Stop bits:</translation > </message>
                                                                                                                                    < message > <source>Slave ID: </source><translation>Slave ID:</translation > </message>
                                                                                                                                        < message > <source>Connecting…</source><translation>Đang kết nối…</translation > </message>
                                                                                                                                            < message > <source>Disconnect < /source><translation>Ngắt kết nối</translation > </message>
                                                                                                                                            < message > <source>Connect < /source><translation>Kết nối</translation > </message>
                                                                                                                                            </context>
                                                                                                                                            < context >
                                                                                                                                            <name>ModbusTesterTaskBar.qml </name>
                                                                                                                                            < message > <source>Connecting…</source><translation>Đang kết nối…</translation > </message>
                                                                                                                                                < message > <source>Disconnect < /source><translation>Ngắt kết nối</translation > </message>
                                                                                                                                                < message > <source>Connect < /source><translation>Kết nối</translation > </message>
                                                                                                                                                < message > <source>Save new sensor < /source><translation>Lưu cảm biến mới</translation > </message>
                                                                                                                                                    < message > <source>Clear table < /source><translation>Xóa bảng</translation > </message>
                                                                                                                                                        < message > <source>Stopping…</source><translation>Đang dừng…</translation > </message>
                                                                                                                                                            < message > <source>Stop scan < /source><translation>Dừng quét</translation > </message>
                                                                                                                                                                < message > <source>Scan range < /source><translation>Quét dải</translation > </message>
                                                                                                                                                                    </context>
                                                                                                                                                                    < context >
                                                                                                                                                                    <name>TesterOperationsTab.qml </name>
                                                                                                                                                                    < message > <source>Register type: </source><translation>Kiểu thanh ghi:</translation > </message>
                                                                                                                                                                        < message > <source>Data type: </source><translation>Kiểu dữ liệu:</translation > </message>
                                                                                                                                                                            < message > <source>Start address: </source><translation>Địa chỉ bắt đầu:</translation > </message>
                                                                                                                                                                                < message > <source>End address: </source><translation>Địa chỉ kết thúc:</translation > </message>
                                                                                                                                                                                    < message > <source>Registers per read: </source><translation>Số thanh ghi / lần đọc: </translation></message >
                                                                                                                                                                                        <message><source>Number of consecutive registers read at each address(1–125).< /source><translation>Số thanh ghi liên tiếp đọc tại mỗi địa chỉ (1–125).</translation > </message>
                                                                                                                                                                                            </context>
                                                                                                                                                                                            < context >
                                                                                                                                                                                            <name>HistoryTaskBar.qml </name>
                                                                                                                                                                                            < message > <source>From: </source><translation>Từ:</translation > </message>
                                                                                                                                                                                                < message > <source>To: </source><translation>Đến:</translation > </message>
                                                                                                                                                                                                    < message > <source>% 1 rows < /source><translation>%1 dòng</translation > </message>
                                                                                                                                                                                                        < message > <source>CSV < /source><translation>CSV</translation > </message>
                                                                                                                                                                                                        </context>
                                                                                                                                                                                                        < context >
                                                                                                                                                                                                        <name>HistoryView.qml </name>
                                                                                                                                                                                                        < message > <source>Close < /source><translation>Đóng</translation > </message>
                                                                                                                                                                                                        < message > <source>Time < /source><translation>Thời gian</translation > </message>
                                                                                                                                                                                                        < message > <source>Sensor < /source><translation>Cảm biến</translation > </message>
                                                                                                                                                                                                        < message > <source>Unit < /source><translation>Đơn vị</translation > </message>
                                                                                                                                                                                                        < message > <source>Value < /source><translation>Giá trị</translation > </message>
                                                                                                                                                                                                        < message > <source>Raw value < /source><translation>Giá trị thô</translation > </message>
                                                                                                                                                                                                            < message > <source>No data.\nAdjust the time range or sensor, then search.< /source><translation>Không có dữ liệu.\nĐiều chỉnh thời gian hoặc cảm biến rồi nhấn tìm.</translation > </message>
                                                                                                                                                                                                                </context>
                                                                                                                                                                                                                < context >
                                                                                                                                                                                                                <name>SettingsView.qml </name>
                                                                                                                                                                                                                < message > <source>UI language: </source><translation>Ngôn ngữ giao diện:</translation > </message>
                                                                                                                                                                                                                    < message > <source>Vietnamese < /source><translation>Tiếng Việt</translation > </message>
                                                                                                                                                                                                                    < message > <source>English < /source><translation>English</translation > </message>
                                                                                                                                                                                                                    < message > <source>Close < /source><translation>Đóng</translation > </message>
                                                                                                                                                                                                                    < message > <source>Add sensor < /source><translation>Thêm cảm biến</translation > </message>
                                                                                                                                                                                                                        < message > <source>Edit sensor < /source><translation>Sửa cảm biến</translation > </message>
                                                                                                                                                                                                                            < message > <source>Name: </source><translation>Tên:</translation > </message>
                                                                                                                                                                                                                                < message > <source>Unit: </source><translation>Đơn vị:</translation > </message>
                                                                                                                                                                                                                                    < message > <source>Slave ID: </source><translation>Slave ID:</translation > </message>
                                                                                                                                                                                                                                        < message > <source>Address: </source><translation>Địa chỉ:</translation > </message>
                                                                                                                                                                                                                                            < message > <source>Register type: </source><translation>Loại thanh ghi:</translation > </message>
                                                                                                                                                                                                                                                < message > <source>Data type: </source><translation>Kiểu dữ liệu:</translation > </message>
                                                                                                                                                                                                                                                    < message > <source>Endian: </source><translation>Endian:</translation > </message>
                                                                                                                                                                                                                                                        < message > <source>Coefficients: </source><translation>Hệ số:</translation > </message>
                                                                                                                                                                                                                                                            < message > <source>Poll interval(s): </source><translation>Chu kỳ đọc (s):</translation > </message>
                                                                                                                                                                                                                                                                < message > <source>Report column: </source><translation>Cột báo cáo:</translation > </message>
                                                                                                                                                                                                                                                                    < message > <source>Active: </source><translation>Kích hoạt:</translation > </message>
                                                                                                                                                                                                                                                                        < message > <source>Cancel < /source><translation>Hủy</translation > </message>
                                                                                                                                                                                                                                                                        < message > <source>Add < /source><translation>Thêm</translation > </message>
                                                                                                                                                                                                                                                                        < message > <source>Save < /source><translation>Lưu</translation > </message>
                                                                                                                                                                                                                                                                        < message > <source>Confirm delete </source><translation>Xác nhận xóa</translation > </message>
                                                                                                                                                                                                                                                                            < message > <source>Delete sensor "%1" ? </source><translation>Xóa cảm biến "%1"?</translation > </message>
                                                                                                                                                                                                                                                                                < message > <source>Delete < /source><translation>Xóa</translation > </message>
                                                                                                                                                                                                                                                                                < message > <source>Report & amp; SFTP < /source><translation>Báo cáo &amp; sFTP</translation > </message>
                                                                                                                                                                                                                                                                                    < message > <source>Sensors < /source><translation>Cảm biến</translation > </message>
                                                                                                                                                                                                                                                                                    < message > <source>Station code: </source><translation>Mã trạm:</translation > </message>
                                                                                                                                                                                                                                                                                        < message > <source>Station name: </source><translation>Tên trạm:</translation > </message>
                                                                                                                                                                                                                                                                                            < message > <source>SFTP host: </source><translation>Địa chỉ sFTP:</translation > </message>
                                                                                                                                                                                                                                                                                                < message > <source>Port: </source><translation>Cổng:</translation > </message>
                                                                                                                                                                                                                                                                                                    < message > <source>Remote folder: </source><translation>Thư mục:</translation > </message>
                                                                                                                                                                                                                                                                                                        < message > <source>Save configuration < /source><translation>Lưu cấu hình</translation > </message>
                                                                                                                                                                                                                                                                                                            < message > <source>Sensor list < /source><translation>Danh sách cảm biến</translation > </message>
                                                                                                                                                                                                                                                                                                                < message > <source>+ Add < /source><translation>+ Thêm</translation > </message>
                                                                                                                                                                                                                                                                                                                < message > <source>Name < /source><translation>Tên</translation > </message>
                                                                                                                                                                                                                                                                                                                < message > <source>Slave < /source><translation>Slave</translation > </message>
                                                                                                                                                                                                                                                                                                                < message > <source>Addr < /source><translation>Địa chỉ</translation > </message>
                                                                                                                                                                                                                                                                                                                < message > <source>Type < /source><translation>Kiểu</translation > </message>
                                                                                                                                                                                                                                                                                                                < message > <source>Interval < /source><translation>Chu kỳ</translation > </message>
                                                                                                                                                                                                                                                                                                                < message > <source>No sensors yet.
                                                                                                                                                                                                                                                                                                                    Press[+ Add] or use the Modbus tester page
to add sensors.</source><translation>Chưa có cảm biến nào.
Nhấn[+ Thêm] hoặc dùng trang thử Modbus
để thêm cảm biến.< /translation></message >
    </context>
    < context >
    <name>DashboardView.qml </name>
    < message > <source>Close < /source><translation>Đóng</translation > </message>
    < message > <source>Stopping…</source><translation>Đang dừng…</translation > </message>
        < message > <source>Stop acquisition < /source><translation>Dừng thu thập</translation > </message>
            < message > <source>Start acquisition < /source><translation>Bắt đầu thu thập</translation > </message>
                < message > <source>No active sensors.
Open Settings to add sensors, then press Start acquisition.</source><translation>Chưa có cảm biến active.
Vào Cài đặt để khai báo, sau đó nhấn Bắt đầu thu thập.< /translation></message >
    </context>
    < context >
    <name>HistoryController </name>
    < message > <source>— All —</source><translation>— Tất cả —</translation > </message>
        < message > <source>Error < /source><translation>Lỗi</translation > </message>
        < message > <source>Invalid date format.Use dd / MM / yyyy.< /source><translation>Định dạng ngày không hợp lệ. Dùng dd/MM / yyyy.< /translation></message >
            <message><source>Start date must be before end date.< /source><translation>Ngày bắt đầu phải trước ngày kết thúc.</translation > </message>
                < message > <source>Notice < /source><translation>Thông báo</translation > </message>
                < message > <source>No data to export.</source><translation>Không có dữ liệu để xuất.</translation > </message>
                    < message > <source>Time < /source><translation>Thời gian</translation > </message>
                    < message > <source>Sensor < /source><translation>Cảm biến</translation > </message>
                    < message > <source>Unit < /source><translation>Đơn vị</translation > </message>
                    < message > <source>Value < /source><translation>Giá trị</translation > </message>
                    < message > <source>Raw value < /source><translation>Giá trị thô</translation > </message>
                        < message > <source>Success < /source><translation>Thành công</translation > </message>
                        < message > <source>Exported { 0 } row(s) to { 1 }.</source><translation>Đã xuất {0} dòng ra {1}.</translation > </message>
                            < message > <source>CSV export failed: { 0 } </source><translation>Xuất CSV thất bại: {0}</translation > </message>
                                < message > <source>No records found in the selected range.< /source><translation>Không tìm thấy dữ liệu trong khoảng thời gian này.</translation > </message>
                                    < message > <source>Query failed: { 0 } </source><translation>Truy vấn thất bại: {0}</translation > </message>
                                        </context>
                                        < context >
                                        <name>SensorListModel </name>
                                        < message > <source>Validation error < /source><translation>Lỗi nhập liệu</translation > </message>
                                            < message > <source>Success < /source><translation>Thành công</translation > </message>
                                            < message > <source>Added sensor '{0}'.< /source><translation>Đã thêm cảm biến '{0}'.</translation > </message>
                                                < message > <source>Error < /source><translation>Lỗi</translation > </message>
                                                < message > <source>Failed to add sensor: { 0 } </source><translation>Thêm cảm biến thất bại: {0}</translation > </message>
                                                    < message > <source>Sensor not found.< /source><translation>Không tìm thấy cảm biến.</translation > </message>
                                                        < message > <source>Updated sensor '{0}'.< /source><translation>Đã cập nhật cảm biến '{0}'.</translation > </message>
                                                            < message > <source>Update failed: { 0 } </source><translation>Cập nhật thất bại: {0}</translation > </message>
                                                                < message > <source>Removed sensor '{0}'.< /source><translation>Đã xóa cảm biến '{0}'.</translation > </message>
                                                                    < message > <source>No sensor found to remove.< /source><translation>Không tìm thấy cảm biến để xóa.</translation > </message>
                                                                        < message > <source>Failed to remove sensor: { 0 } </source><translation>Xóa cảm biến thất bại: {0}</translation > </message>
                                                                            < message > <source>Sensor name cannot be empty.< /source><translation>Tên cảm biến không được để trống.</translation > </message>
                                                                                < message > <source>Unit cannot be empty.< /source><translation>Đơn vị đo không được để trống.</translation > </message>
                                                                                    < message > <source>Slave ID must be between 1 and 247. < /source><translation>Slave ID phải từ 1 đến 247.</translation > </message>
                                                                                        < message > <source>Register address must be between 0 and 65535. < /source><translation>Địa chỉ thanh ghi phải từ 0 đến 65535.</translation > </message>
                                                                                            </context>
                                                                                            < context >
                                                                                            <name>SettingsController </name>
                                                                                            < message > <source>Error < /source><translation>Lỗi</translation > </message>
                                                                                            < message > <source>Could not load configuration: { 0 } </source><translation>Không thể tải cấu hình: {0}</translation > </message>
                                                                                                < message > <source>Validation error < /source><translation>Lỗi nhập liệu</translation > </message>
                                                                                                    < message > <source>Success < /source><translation>Thành công</translation > </message>
                                                                                                    < message > <source>Configuration saved.< /source><translation>Đã lưu cấu hình.</translation > </message>
                                                                                                        < message > <source>Failed to save configuration: { 0 } </source><translation>Lưu cấu hình thất bại: {0}</translation > </message>
                                                                                                            < message > <source>Poll interval must be at least 1 second.< /source><translation>Chu kỳ polling phải &gt;= 1 giây.</translation > </message>
                                                                                                                < message > <source>FTP port must be between 1 and 65535. < /source><translation>Cổng FTP phải trong khoảng 1-65535.</translation > </message>
                                                                                                                    </context>
                                                                                                                    < context >
                                                                                                                    <name>DashboardController </name>
                                                                                                                    < message > <source>Error < /source><translation>Lỗi</translation > </message>
                                                                                                                    < message > <source>No system configuration yet.Open Settings to set up.< /source><translation>Chưa có cấu hình hệ thống. Vào Cài đặt để thiết lập.</translation > </message>
                                                                                                                        < message > <source>No active sensors.Open Settings to add sensors.< /source><translation>Chưa có cảm biến active. Vào Cài đặt để khai báo.</translation > </message>
                                                                                                                            < message > <source>Could not start polling: { 0 } </source><translation>Không thể bắt đầu polling: {0}</translation > </message>
                                                                                                                                < message > <source>Acquiring…</source><translation>Đang thu thập…</translation > </message>
                                                                                                                                    < message > <source>Stopping…</source><translation>Đang dừng…</translation > </message>
                                                                                                                                        < message > <source>Stopped < /source><translation>Đã dừng</translation > </message>
                                                                                                                                        < message > <source>Connection lost — retrying…</source><translation>Mất kết nối — đang thử lại…</translation > </message>
                                                                                                                                            < message > <source>Stopped(worker exited) < /source><translation>Dừng (worker thoát)</translation > </message>
                                                                                                                                            < message > <source>Ready < /source><translation>Sẵn sàng</translation > </message>
                                                                                                                                            </context>
                                                                                                                                            < context >
                                                                                                                                            <name>DashboardTaskBar.qml </name>
                                                                                                                                            < message > <source>Stopping…</source><translation>Đang dừng…</translation > </message>
                                                                                                                                                < message > <source>Stop acquisition < /source><translation>Dừng thu thập</translation > </message>
                                                                                                                                                    < message > <source>Start acquisition < /source><translation>Bắt đầu thu thập</translation > </message>
                                                                                                                                                        < message > <source>Modbus read errors: % 1 < /source><translation>Lỗi đọc Modbus: %1</translation > </message>
                                                                                                                                                            < message > <source>No read errors < /source><translation>Không có lỗi đọc</translation > </message>
                                                                                                                                                                </context>
                                                                                                                                                                < context >
                                                                                                                                                                <name>ReportController </name>
                                                                                                                                                                < message > <source>Report: running < /source><translation>Báo cáo: đang chạy</translation > </message>
                                                                                                                                                                    < message > <source>Report: stopped < /source><translation>Báo cáo: đã dừng</translation > </message>
                                                                                                                                                                        < message > <source>Report: worker exited < /source><translation>Báo cáo: worker thoát</translation > </message>
                                                                                                                                                                            </context>
                                                                                                                                                                            </TS>
